/*
 * Copyright (c) 2024-2025 European Commission
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import com.vanniktech.maven.publish.AndroidMultiVariantLibrary
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.serialization)
    id("kotlin-parcelize")
    alias(libs.plugins.dokka)
    alias(libs.plugins.maven.publish)
}

val NAMESPACE: String by project
val GROUP: String by project
val POM_SCM_URL: String by project

android {
    namespace = NAMESPACE
    group = GROUP
    compileSdk = 35

    defaultConfig {
        minSdk = 26

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(libs.versions.java.get())
        targetCompatibility = JavaVersion.toVersion(libs.versions.java.get())
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.fromTarget(libs.versions.java.get()))
        freeCompilerArgs.addAll(
            "-opt-in=kotlin.RequiresOptIn",
        )
    }
}

dependencies {
    api(libs.eudi.document.manager)
    api(libs.eudi.iso18013.data.transfer)

    // multipaz library
    api(libs.multipaz.android) {
        exclude(group = "org.bouncycastle")
        exclude(group = "io.ktor")
    }

    implementation(libs.androidx.credentials)
    implementation(libs.androidx.credentials.registry.provider)

    // CBOR
    implementation(libs.cbor)
    implementation(libs.upokecenter.cbor)

    // Bouncy Castle (used by upstream multipaz crypto)
    implementation(libs.bouncy.castle.prov)
    implementation(libs.bouncy.castle.pkix)

    implementation(libs.kotlinx.io.core)
    implementation(libs.kotlinx.io.bytestring)

    // androidx.core for Bitmap.scale extension used in icon rescaling
    implementation(libs.core.ktx)

    testImplementation(libs.kotlin.test.junit)
    testImplementation(libs.mockk)
    testImplementation(libs.json)
    testImplementation(libs.kotlin.coroutines.test)
    testImplementation(libs.robolectric)
}

// Publishing

mavenPublishing {
    configure(
        AndroidMultiVariantLibrary(
            sourcesJar = true,
            publishJavadocJar = true,
            setOf("release")
        )
    )
    pom {
        ciManagement {
            system = "github"
            url = "${POM_SCM_URL}/actions"
        }
    }
}

// handle java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9
// when publishing module
afterEvaluate {
    tasks.named("javaDocReleaseGeneration").configure {
        enabled = false
    }
}

// Dokka generation

tasks.dokkaGfm.configure {
    val outputDir = file("$rootDir/docs/dcapi-manager")
    doFirst { delete(outputDir) }
    outputDirectory.set(outputDir)
}

tasks.register<Jar>("dokkaHtmlJar") {
    group = "documentation"
    dependsOn(tasks.dokkaHtml)
    from(tasks.dokkaHtml.flatMap { it.outputDirectory })
    archiveClassifier.set("html-docs")
    description = "Assembles a JAR containing the HTML documentation generated by Dokka."
}

tasks.register<Jar>("dokkaJavadocJar") {
    group = "documentation"
    dependsOn(tasks.dokkaJavadoc)
    from(tasks.dokkaJavadoc.flatMap { it.outputDirectory })
    archiveClassifier.set("javadoc")
    description = "Assembles a JAR containing the Javadoc-style documentation generated by Dokka."
}

// Build documentation
tasks.register<Task>("buildDocumentation") {
    group = "documentation"
    dependsOn("dokkaGfm")
    description = "Aggregates documentation tasks (Dokka GFM)."
}
tasks.assemble.configure {
    finalizedBy("buildDocumentation")
}
